export type Stay = {
  id: string;
  host_id: string;
  name: string;
  description: string;
  address: string;
  region: string;
  category: string;
  price_per_night: number;
  max_guests: number;
  bedrooms: number;
  beds: number;
  bathrooms: number;
  amenities: string[];
  tags: string[];
  images: string[];
  host_name: string | null;
  host_phone: string | null;
  is_active: boolean;
  created_at: string;
  updated_at: string;
  rating: number;
  reviews: number;
  superhost: boolean;
};
